version: "3"

services:
  andino_slam_sim:
    image: "andino_inorbit_rmf:latest"
    container_name: "andino_slam_sim"
    privileged: true
    ipc: host
    pid: host
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros_pkgs:/home/$USER/ws/src
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

  inorbit_agent:
    image: "inorbitai/agent:ros-jazzy-4.23.0"
    container_name: "inorbit_agent"
    privileged: true
    ipc: host
    pid: host       
    network_mode: "host"
    depends_on:
      - "andino_slam_sim"
    restart: "always"
    volumes:
      - ./inorbit/data:/root/.inorbit/local/
      - ./inorbit/agent.env.sh:/root/.inorbit/local/agent.env.sh